server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: {db_username}
    password: {db_password}
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: ${mysecretkey}
  expiration: 3600000

