server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mission_db?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 0000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: mysecretkeymysecretkeymysecretkey
  expiration: 3600000
  refresh-expiration: 86400000
