server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kuit4serverauth
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: janghyunjun
    password: Wonjoon1206!
#  h2:
#    console:
#      enabled: true
#      path: /h2-console


jwt:
  secret: mysecretkey123mysecretkey123mysecretkey123mysecretkey123mysecretkey123mysecretkey123
  expiration: 3600000

