server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:mission_db;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: mysecretkeymysecretkeymysecretkeymysecretkeymysecretkey
  expiration: 3600000

