server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mission_db?characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  sql:
    init:
      mode: always
      platform: mysql

jwt:
  secret: mysecretkeymysecretkeymysecretkeymysecretkey
  expiration: 3600000

