server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/KUIT?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 0000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

jwt:
  secret: ZGVtbzEyMzQ1Njc4OWFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6YWJjZGVmZw==
  accessExpiration: 3600000
  refreshExporation: 86400000
