server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kuit_week9?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ksg1227
    password: skcjswo00

jwt:
  secret: mysecretkey01234567890123456789012345678901234
  expiration: 100000
  refresh-expiration: 60480000


