server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BaeminDB
    username: idwjddus
    password: 'Dlwjddus123@'
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
jwt:
  secret: mysecretkey
  expiration-ms: 3600000 # 1 hour