server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/delivery?characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  sql:
    init:
      mode: always
      platform: mysql

jwt:
  secret: mysecretkeymysecretkeymysecretkeymysecretkey
  expiration: 3600000

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true