server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:mission_db;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

jwt:
  secret: your-very-long-and-secure-secret-key-for-jwt-signing
  expiration: 3600000

